language: php
php:
  - 5.6
services:
  - memcached

before_script:
  - composer self-update
  - composer install
  - php artisan serve --host 0.0.0.0 & > /dev/null
  - sleep 5
  - wget http://www.browserstack.com/browserstack-local/BrowserStackLocal-linux-x64.zip
  - unzip BrowserStackLocal-linux-x64.zip
  - ./BrowserStackLocal BS_AUTH_KEY -forcelocal & > /dev/null
  - sleep 10

script:
  - rake

matrix:
  fast_finish: true
